### ISSUE TITLE
bind key for specific mode

### ISSUE THREAD

**Issue by blaenk** [justbur/emacs-bind-map#4]
evil-leader seems to support this:

``` elisp
(evil-leader/set-key-for-mode 'emacs-lisp-mode "b" 'byte-compile-file)
```

Any chance we can get something like that here?

**Comment by justbur** [comment]
It's supported using the `:major-modes` key. You could do something like this

```elisp

(bind-map my-emacs-lisp-map
  :major-modes (emacs-lisp-mode)
  :keys ("M-RET")
  :evil-keys (","))
```

**Comment by justbur** [comment]
and then 

```elisp
(define-key my-emacs-lisp-map "b" 'byte-compile-file)
```

**Comment by blaenk** [comment]
Right I saw that but it seems like a hassle to have to define a new map each time just to do that (and possibly have to set it to a different key?), whereas evil-leader doesn't seem to require that. I think it's modifying the map itself or something.

**Comment by justbur** [comment]
It's not each time. It's just once for each mode. If you think it's a hassle you can look at [general](https://github.com/noctuid/general.el) which is designed differently and may work for you. This library is designed to define keymaps that apply in various situations. That's all.

**Comment by blaenk** [comment]
Fair enough, thanks for creating this all the same.

Would one have to set the new map to a different prefix though? For example say my leader map is at "SPC" but if I want to create binds for a certain mode, I'd create a map for that mod like you say, but wouldn't I have to set it to something other than "SPC"?

**Comment by blaenk** [comment]
What I meant by each time was that of course. I may have to create one or two binds for one mode, again for another, and so on. So each time I wanted to do that I'd have to create an entirely separate map is what I'm saying. Of course once created you could bind onto it as much as you want.

**Comment by justbur** [comment]
Sorry, can you give me a more concrete example? Multiple maps can use the same "leader key" that's not a problem. I could add a `:bindings` keyword to `bind-map`. I almost did that anyway. That would mean one statement to declare a map and bind keys to it. The only real differences between this and `evil-leader` is that you give a name for the map, where in `evil-leader` it's "anonymous" because you don't come up with a keymap name for a mode. That and you declare the prefix. I could add a default prefix I guess.

**Comment by blaenk** [comment]
I think I misunderstood the README. I was under the impression that I had to set each new major-mode-specific map to a different "leader key", since the README shows the base leader map at `M-m` and then shows the `:major-modes` feature for an elisp specific one but places it at `M-m m`, so I figured it had to be at a different location.

With respect to what I believe may be a hassle is this.

Imagine you only really need to create bindings for one specific mode, like elisp, ok so you create a new map for it, then you can create 1,000 binds to it and that's all fine because you only had to create the map once. However, the converse is more likely I believe (at least, in my situation): to put it in a hyperbolic manner, imagine 1,000 modes for which you want to create 1 custom binding each. That would mean you have to create 1,000 separate "mode-specific" maps just to create the 1 bind for each of those. Is that correct?

Clearly that's an exaggeration, but that was the gist of my concern. If so, it's not the end of the world, but I filed this because I was curious if perhaps I was mistaken and there is a more straightforward way like evil-leader does.

**Comment by justbur** [comment]
evil-leader defines one map for each major-mode and allows one leader if I remember right. bind-map obviously allows this plus more with a little repetition in declaring the maps. If you want to propose a new API I'd be happy to consider it. Is it the naming of the maps you don't like (if so, see `bind-map-for-major-mode`) or repeating the leader keys? 

bind-map makes less assumptions, but is more flexible and more powerful (you can apply the same map to major and minor modes for instance).

**Comment by blaenk** [comment]
Alright so for example, my default map is:

``` elisp
(bind-map blaenk/leader-map
          :keys ("M-m")
          :evil-keys ("SPC")
          :evil-states (normal motion visual))
```

And then I want to create some bindings for markdown-mode, so I create a map for it but I want it to otherwise have the same settings as my default map: same leader key, same evil states, same evil keys. So I basically have to retype or copy that (they're in different files) before I can actually use them:

``` elisp
(bind-map blaenk/markdown-map
  :keys ("M-m")
  :evil-keys ("SPC")
  :evil-states (normal motion visual)
  :major-modes (markdown-mode gfm-mode))

(bind-key "k" 'beginning-of-defun blaenk/markdown-map)
(bind-key "j" 'end-of-defun blaenk/markdown-map)
```

Then repeat that for each of the other modes I may want to create bindings for. That seems like it may be error prone if I mess something up when retyping the same settings. Perhaps we can have some sort of `(bind-map-derive blaenk/markdown-map ...)` which takes on the same settings along with any changes you may introduce, so you could get straight to using it:

``` elisp
(bind-map-derive blaenk/leader-map
  :major-modes (markdown-mode gfm-mode))

(bind-key "k" 'beginning-of-defun blaenk/markdown-map)
(bind-key "j" 'end-of-defun blaenk/markdown-map)
```

That might improve the ergonomics a bit. But if this is beyond the scope of your package or you disagree, no problem, this was mostly out of curiosity to see if there was actually a better way and I wasn't aware.

**Comment by justbur** [comment]
There's already a variable for the default evil states to use. I'd be happy
to add default keys so you could leave those two unspecified. That would be
the same amount of typing. The default thing is easy but I kind of like the
derive idea if you want me to go that route.

**Comment by blaenk** [comment]
I hacked together a macro that helps a bit for now, `bind-keys-for-major-modes`. It basically delegates to bind-key's `bind-keys` which takes an alist of binds. Before that though it generates a bind map name and creates one with the same settings. The problem is that it hard-codes the settings, so it's not very generally applicable, but it works for now.

``` elisp
(defmacro bind-keys-for-major-modes (modes &rest binds)
  (let* ((mode-list (-map (lambda (mode)
                            (s-chop-suffix "-mode" (symbol-name mode)))
                          modes))
         (modes-string (s-join "-" mode-list))
         (map-name (intern (concat "blaenk/" modes-string "-map"))))
    `(progn
       (bind-map ,map-name
         :keys ("M-m")
         :evil-keys ("SPC")
         :evil-states (normal motion visual)
         :major-modes ,modes)
       (bind-keys :map ,map-name ,@binds))))

(put 'bind-keys-for-major-modes 'lisp-indent-function 'defun)
```

Example use:

``` elisp
(bind-keys-for-major-modes (markdown-mode gfm-mode)
  ("k" . beginning-of-defun)
  ("j" . end-of-defun))
```

Oh yeah I know that those are the default evil states too. I think I originally wrote them in explicitly anyways so that I would remember that I could change them if I wanted to.

**Comment by justbur** [comment]
Just added `bind-map-for-modes-derived` and a `:bindings` keyword.

Here's a rough example.

```elisp
(bind-map base-map
  :evil-keys ("SPC")
  :bindings ("a" 'fa
             "b" 'fb))

(bind-map-for-modes-derived mode-map base-map
  :major-modes (markdown-mode)
  :bindings ("c" 'fc
             "d" 'fd))
```

The second one pulls properties out of `base-map` to automate the process.

**Comment by blaenk** [comment]
Looks good!

Just an idea, what would you think about just adding a `:derive-from` or similar property that `bind-map` understands, then you can just use the same thing:

``` elisp
(bind-map base-map
  :evil-keys ("SPC")
  :bindings ("a" 'fa
             "b" 'fb))

(bind-map mode-map
  :derive-from base-map
  :major-modes (markdown-mode)
  :bindings ("c" 'fc
             "d" 'fd))
```

**Comment by blaenk** [comment]
It would also be more generally applicable, in case the idea of "deriving" from keymaps ends up being useful for other things that I can't think of.

**Comment by justbur** [comment]
I like the idea. I'll try it and maybe remove the macro I just added

**Comment by blaenk** [comment]
Cool! By the way, perhaps there's a better name for the key of such a property, like `:inherit`. In retrospect I think `:derive-from` is too much typing, `:derive` maybe.

**Comment by blaenk** [comment]
Or `:copy`, I don't know, perhaps you can come up with something better.

**Comment by justbur** [comment]
I decided to not go with the keyword, because the way it's implemented is sufficiently different. It will only inherit four keywords not all of them, so I thought it would be confusing as just a keyword. At least the separate command encourages people to think about it as being different and consulting the docstring. I also changed the name to `bind-map-for-mode-inherit`. It's not great, but I think it's a little better. Thanks for the suggestions.

**Comment by blaenk** [comment]
Alright, thanks!

**Comment by justbur** [comment]
Thanks for the suggestions. I'll update the readme soon.

**Comment by rgrinberg** [comment]
@justbur Friendly ping to update the docs. This is useful for me as well.

**Comment by justbur** [comment]
@rgrinberg Thanks. I just did
