### ISSUE TITLE
correctly binding return after a key sequence

### ISSUE THREAD

**Issue by ninrod** [justbur/emacs-bind-map#5]
How do I bind the `<CR>` key after a sequence, as demostrated below?

```lisp
(bind-map-set-keys org-map
  "ml" 'org-metaright
  "mh" 'org-metaleft
  "mj" 'org-metadown
  "mk" 'org-metaup

 ;; this does not work. how do properly bind return?
 ;; mRET? m<RET>?
  "m<CR>" 'org-meta-return
)
```

**Comment by justbur** [comment]
You probably either want "m RET" or "<M-return>". "<CR>" is not a recognized symbol for a key as far as I know.

**Comment by ninrod** [comment]
@justbur. `m RET` solved the issue.

thank you for you work in this package. awesome stuff, it's a core dependency of my config.

**Comment by justbur** [comment]
> thank you for you work in this package. awesome stuff, it's a core dependency of my config.

Great. I'm happy to hear that
